server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /api/summary {
        proxy_pass http://192.168.1.116:31054/api/summary;
        proxy_set_header Host 192.168.1.116;
        proxy_set_header Accept application/json;
        add_header Access-Control-Allow-Origin *;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}